[package]
name = "akamai"
version = "0.1.0"
authors = ["Clément Renault <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
chrono = "0.4.6"
hmac = "0.7.0"
reqwest = "0.9.10"
sha2 = "0.8.0"
url = "1.7.2"
uuid = "0.7.2"
structopt = "0.2.14"
serde_json = "1.0.39"
